<section class="contents">
            <ul class="ul_mhome">
                <li class="m_clients">
                <a href="<?php echo $this->baseUrl();?>/clients" class="am_clients">Clients</a>
                </li>
                <li class="m_contact">
    			<a href="<?php echo $this->url(array('controller'=>'contacts',
                                                            ));?>" class="am_contact">Contacts</a>
                </li>
                <li class="m_emp">
                <a href="<?php echo $this->url(array('controller'=>'employees',
                                                            ));?>" class="am_reserved">Reserved</a>
                </li>
                <li class="m_partners">
    			<a href="<?php echo $this->url(array('controller'=>'partners',
                                                            ));?>" class="am_emp">Employees</a></td>
                </li>
                <li class="m_home">
    			<a href="<?php echo $this->url(array('controller'=>'index',
                                                            ));?>" class="am_emp">Home</a></td>
                </li>
            </ul>
</section>
